spring:
  main:
    web-application-type: reactive
  application:
    name: spring-ai-ollama
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        model: nomic-embed-text
      chat:
        model: qwen2.5:7b
        memory:
          repository:
            jdbc:
              initialize-schema: always
              platform: postgres
    mcp:
      client:
        enabled: true
        base-url: http://localhost:8081
        toolcallback:
          enabled: true
        name: my-mcp-client
        version: 1.0.0
        type: SYNC
        request-timeout: 20s
        streamable-http:
          connections:
            rag-server:
              url: http://localhost:8081

    vectorstore:
      pgvector:
        initialize-schema: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: raguser
    password: ragpass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    # 1. See Ollama's reasoning and tool selection
    #org.springframework.ai.chat: DEBUG

    # 2. See the local tool execution and callback triggers
    org.springframework.ai.tool: TRACE

    # 3. See the specific MCP client JSON-RPC payloads going to port 8081
    org.springframework.ai.mcp: TRACE

    # 4. (Optional) See the raw HTTP web client streams
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE