spring:
  main:
    web-application-type: reactive
  application:
    name: spring-ai-ollama
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        model: nomic-embed-text
      chat:
        model: qwen2.5:7b
    vectorstore:
      pgvector:
        initialize-schema: true

  datasource:
    url: jdbc:postgresql://postgres:5432/ragdb
    username: raguser
    password: ragpass

logging:
  level:
    org.springframework.ai: DEBUG