spring:
  main:
    web-application-type: reactive
  application:
    name: spring-ai-ollama
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: llama3